url: http://greg.nokes.name
title: DaRoost
description: 'A wayward journey into the depths of sanity'

# theme: type-on-strap
# theme: minima
#theme: jekyll-theme-hydeout
theme: plainwhite


author:
  name:           'Greg Nokes'
  url:            https://twitter.com/tsykoduk

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - kramdown

markdown:         kramdown
highlighter:      rouge
  
sidebar_home_link:  true
paginate:         5

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile','to_be_cleaned','static.json','update.sh', 'app.json']
