url: http://greg.nokes.name
name: DaRoost
description: >
  A wayward journey into the depths of
  sanity

theme: hydeout
plugins: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']